#!/usr/bin/env node
/**
 * Derive one identity for a build and write it where both halves can import it.
 *
 * Two things need it. The AudioWorklet is fetched by URL rather than imported,
 * so Vite cannot fingerprint it and a browser will happily keep an old copy --
 * its hash goes in the query string. And a tab left open across a deploy keeps
 * running old code forever, so the Worker reports the build id and the page
 * compares. Both failures look the same from the outside: one device playing
 * by different rules with perfectly healthy-looking telemetry.
 */
import { createHash } from "node:crypto";
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const read = (p) => readFileSync(join(root, p));

const workletHash = createHash("sha256").update(read("public/live-processor.js"))
  .digest("hex").slice(0, 12);

const buildId = createHash("sha256")
  .update(workletHash)
  .update(read("src/audio/engine.ts"))
  .update(read("src/audio/clock.ts"))
  .update(read("src/audio/room.ts"))
  .update(read("src/shared/protocol.ts"))
  // The headers decide whether the page is cross-origin isolated, and with
  // it whether shared-memory audio exists at all -- that is identity too.
  .update(read("public/_headers"))
  .digest("hex")
  .slice(0, 12);

writeFileSync(
  join(root, "src/shared/build.ts"),
  `// Generated by scripts/build-id.mjs -- do not edit.\n` +
    `export const BUILD_ID = ${JSON.stringify(buildId)};\n` +
    `export const WORKLET_VERSION = ${JSON.stringify(workletHash)};\n`,
);

console.log(`build ${buildId}  worklet ${workletHash}`);
